/**
 * Self-consistency test for the ported client challenge engine.
 *
 * The port only has to agree with ITSELF: a set generated by `generateSet` must
 * validate (via `validateLocal`) with the answers the same seed/index re-derives.
 * We prove that here for both Speed Math and Memory — the two offline modes.
 *
 * The repo ships no test runner (no vitest/jest, no `yarn test`). To keep this
 * runnable AND to keep `tsc --noEmit` green (a framework import would fail to
 * resolve), the harness is a tiny self-contained asserter with no external deps.
 * Run it by transpiling to CJS and executing with node — see the task report.
 */
import { generateSet, validateLocal, SeededRng } from './index';

let passed = 0;
let failed = 0;
const failures: string[] = [];

function check(cond: boolean, msg: string): void {
  if (cond) {
    passed++;
  } else {
    failed++;
    failures.push(msg);
  }
}

// ── Speed Math: generate a set, re-derive answers, validate ──────────────────
function speedMathSelfConsistency(): void {
  const matchSeed = 'test-seed-math-001';
  const mode = 'speed_math' as const;
  const difficulty = 3;
  const set = generateSet({ matchSeed, mode, count: 10, difficulty });

  check(set.challenges.length === 10, 'math: set has 10 challenges');
  check(set.matchSeed === matchSeed, 'math: echoes matchSeed');
  check(set.mode === mode, 'math: echoes mode');

  for (const c of set.challenges) {
    check(!('answer' in c), `math[${c.index}]: answer stripped from client set`);
    check(c.type === 'math', `math[${c.index}]: type is math`);
    check(typeof c.prompt.expression === 'string', `math[${c.index}]: has expression`);

    // Re-derive the correct answer the same way validate does, from the expression.
    const correct = evalExpression(c.prompt.expression as string);
    const ok = validateLocal({ matchSeed, mode, difficulty, index: c.index, answer: correct, elapsedMs: 500 });
    check(ok.correct === true, `math[${c.index}]: correct answer validates`);
    check(ok.score > 0, `math[${c.index}]: correct answer scores > 0 (got ${ok.score})`);

    // A deliberately wrong answer must fail and score 0.
    const wrong = correct + 1;
    const bad = validateLocal({ matchSeed, mode, difficulty, index: c.index, answer: wrong, elapsedMs: 500 });
    check(bad.correct === false, `math[${c.index}]: wrong answer rejected`);
    check(bad.score === 0, `math[${c.index}]: wrong answer scores 0 (got ${bad.score})`);
  }
}

// ── Memory: sequence is client-visible in prompt; taps back should validate ──
function memorySelfConsistency(): void {
  const matchSeed = 'test-seed-memory-001';
  const mode = 'memory' as const;
  const difficulty = 3;
  const set = generateSet({ matchSeed, mode, count: 10, difficulty });

  check(set.challenges.length === 10, 'memory: set has 10 challenges');

  for (const c of set.challenges) {
    check(!('answer' in c), `memory[${c.index}]: answer stripped from client set`);
    check(c.type === 'memory', `memory[${c.index}]: type is memory`);
    const seq = c.prompt.sequence as number[] | undefined;
    check(Array.isArray(seq) && seq.length >= 3, `memory[${c.index}]: has a sequence`);

    // The player taps the flashed sequence back — that IS the answer.
    const ok = validateLocal({ matchSeed, mode, difficulty, index: c.index, answer: seq, elapsedMs: 500 });
    check(ok.correct === true, `memory[${c.index}]: tapped sequence validates`);
    check(ok.score > 0, `memory[${c.index}]: correct sequence scores > 0 (got ${ok.score})`);

    // Perturb the sequence -> must fail and score 0.
    const wrong = (seq ?? []).slice();
    wrong[0] = ((wrong[0] ?? 0) + 1) % 9;
    const bad = validateLocal({ matchSeed, mode, difficulty, index: c.index, answer: wrong, elapsedMs: 500 });
    check(bad.correct === false, `memory[${c.index}]: perturbed sequence rejected`);
    check(bad.score === 0, `memory[${c.index}]: perturbed sequence scores 0 (got ${bad.score})`);
  }
}

// ── Determinism: same seed -> identical set ──────────────────────────────────
function determinism(): void {
  const a = generateSet({ matchSeed: 'dupe', mode: 'speed_math', count: 5, difficulty: 4 });
  const b = generateSet({ matchSeed: 'dupe', mode: 'speed_math', count: 5, difficulty: 4 });
  check(
    JSON.stringify(a) === JSON.stringify(b),
    'determinism: same seed yields an identical set',
  );

  // Two seeds SHOULD differ (guards against a broken/constant rng).
  const rngA = new SeededRng('seed-a');
  const rngB = new SeededRng('seed-b');
  check(rngA.nextInt(0, 1_000_000) !== rngB.nextInt(0, 1_000_000), 'determinism: distinct seeds diverge');
}

/**
 * Evaluate a generated math expression string. The generator uses the glyphs
 * `+`, `−` (U+2212), `×`, `÷`; map them to JS operators. Only ever runs on our
 * own generated, integer-only expressions.
 */
function evalExpression(expr: string): number {
  const m = expr.match(/^(\d+)\s*(.)\s*(\d+)$/u);
  if (!m) throw new Error(`unparseable expression: ${expr}`);
  const a = Number(m[1]);
  const b = Number(m[3]);
  switch (m[2]) {
    case '+':
      return a + b;
    case '-':
    case '−':
      return a - b;
    case '×':
      return a * b;
    case '÷':
      return a / b;
    default:
      throw new Error(`unknown operator in: ${expr}`);
  }
}

/** Run every self-consistency check. Returns true iff all pass. */
export function runChallengeEngineSpec(): { ok: boolean; passed: number; failed: number; failures: string[] } {
  speedMathSelfConsistency();
  memorySelfConsistency();
  determinism();
  return { ok: failed === 0, passed, failed, failures };
}
